spring:
  main:
    allow-circular-references: true
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: manual
        default-requeue-rejected: false
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    database: MYSQL
    generate-ddl: false
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate.cache.use_second_level_cache: false
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.show_sql: false
      hibernate.format_sql: false
      hibernate.jdbc.batch_size: 500
      hibernate.order_inserts: true
      hibernate.order_updates: true
  datasource:
    databaseDriverName: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    maxPool: 5
    maxIdle: 4
    minIdle: 0

  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/changelog-master.yml

